Repository SeitaBV/timely-beliefs, pull requests merged in 2020-08, with the labels that each got.

#19 Freeze dependencies
  .travis.yml
  Makefile
  requirements.txt
  timely_beliefs/tests/test_belief_io.py
Labels: Continuous integration

#21 Small fix and usage conveniences for mixin support
  .pre-commit-config.yaml
  README.md
  timely_beliefs/__init__.py
  timely_beliefs/beliefs/classes.py
  timely_beliefs/beliefs/probabilistic_utils.py
  timely_beliefs/beliefs/utils.py
  timely_beliefs/sensors/classes.py
  timely_beliefs/sensors/utils.py
  timely_beliefs/tests/test_db_subclassing.py
  timely_beliefs/visualization/utils.py
Labels: Database support

#14 Update handling of resampling resolutions
  setup.py
  timely_beliefs/beliefs/classes.py
  timely_beliefs/beliefs/utils.py
  timely_beliefs/tests/test_df_resampling.py
  timely_beliefs/utils.py
Labels: Resampling
