Repository SeitaBV/timely-beliefs, pull requests merged in 2024-03, with the labels that each got.

#168 fix: apply event timing and belief timing filters to subquery to find the most recent event
  timely_beliefs/beliefs/classes.py
Labels: bug

#171 Feature/upsample to instantaneous
  timely_beliefs/beliefs/classes.py
  timely_beliefs/beliefs/utils.py
  timely_beliefs/tests/test_df_resampling.py
Labels: Resampling

#173 Pop `dayfirst` attribute before read_excel.
  timely_beliefs/beliefs/utils.py
Labels: bug

#174 Ceil, round or floor `event_start` on `read_csv` function.
  timely_beliefs/beliefs/utils.py
Labels: enhancement

#172 add `at_date_annually` knowledge horizon function
  timely_beliefs/sensors/func_store/knowledge_horizons.py
  timely_beliefs/sensors/func_store/test_knowledge_horizons.py
  timely_beliefs/sensors/func_store/utils.py
Labels: enhancement
